### ISSUE TITLE
Support midi files

### ISSUE THREAD

**Issue by smithdtyler** [smithdtyler/prettygoodmusicplayer#105]

**Comment by undu** [comment]
I see that there's another issue about supporting another file extension: https://github.com/smithdtyler/prettygoodmusicplayer/issues/86

Right now there's a static list that contains a list of supported file extensions (in Utils.java). Maybe it would be a good idea to build a list of supported formats using the available media decoders in the system, this way the player can support any audio format that the underlying base system can and these issues would hopefully disappear. ;)

This should be possible using [MediaCodecList](http://developer.android.com/reference/android/media/MediaCodecList.html) and [MediaCodecInfo](http://developer.android.com/reference/android/media/MediaCodecInfo.html), there's an illustrative piece of code example in the last one. Tentatively, the accepted mimeTypes should be the ones that start with "audio/" and the codec they're in isn't an encoder.

Since MediaCodecInfo works with mime types instead of file extensions [MimeTypeMap](http://developer.android.com/reference/android/webkit/MimeTypeMap.html) should be used to convert between file extensions and mime type using, for example,
````java
MimeTypeMap.getSingleton().getMimeTypeFromExtension(String extension);
````
or
````java
MimeTypeMap.getSingleton().getExtensionFromMimeType(String mimeType);
````

**Comment by undu** [comment]
I've got the code that gets all the media types in the system working, the problem is that MimeTypeMap is very limited, it only returns one extension per media type, and most of the type it doesn't return any at all.

I'll try to get a wrapper that supports multiple file extensions per media type and adds file extensions that are interesting for the program.
