### ISSUE TITLE
Folders not showing with [] 

### ISSUE THREAD

**Issue by michal-sapsa** [smithdtyler/prettygoodmusicplayer#75]
When folder starts with [ it's getting ignored,  ending not showing up.

**Comment by smithdtyler** [comment]
I'll try this out tomorrow.

**Comment by smithdtyler** [comment]
Utils.java currently has code for checking for valid folder and file names. I'm guessing I put this in because I need to display the names in a ListView. 

I'll test allowing special characters and make sure it doesn't cause issues. If it does I'll strip them out before displaying the names, but still allow the folders. 

```
	static boolean isValidAlbumDirectory(File dir) {
		if (dir == null) {
			return false;
		}

		if (!dir.isDirectory()) {
			return false;
		}

		String name = dir.getName();
		if (!name.matches("^([A-Z]|[a-z]|[0-9]).+")) {
			return false;
		}

		return true;
	}

	static boolean isValidSongFile(File song) {
		if (song == null) {
			return false;
		}

		if (!song.isFile()) {
			return false;
		}

		String name = song.getName();
		// needs to start with a letter or number
		if (!name.matches("^([A-Z]|[a-z]|[0-9]).+")) {
			return false;
		}

		// Needs to end with one of the legal formats
		for (String ending : legalFormatExtensions) {
			if (name.endsWith("." + ending)) {
				return true;
			}
		}

		return false;
	}
```

**Comment by smithdtyler** [comment]
Seems to be working fine without the name filters. The fix has been committed to master and will be included in the next revision.
